### ISSUE TITLE
Try to stay consistent with the CSS code formatting and structure.

### ISSUE THREAD

**Issue by josephtkim** [bransam72783/teacozy2#4]
There seems to be a lot of extra spacing and some inconsistency in your CSS code formatting. Here is how you can format the code with most of the extra spacing removed and with proper formatting:

```css
/* GLOBALS */
* {
  margin: 0;
  padding: 0;
  color: seashell;
  font-family: helvetica;
}

/* HEAD BEGIN*/
header {
  opacity: 1;
  background-color: black;
  border-bottom: 1px solid seashell;
  position: fixed;
  width: 100%;
}

.headcontent {
  display: flex;
  align-items: center;
  height: 69px;
}
```
